---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r}
library(topGO)
library(stringr)
library(org.Mm.eg.db)
diff_genes = readRDS("data/sig_regulated_genes.rds")
x = as.list(org.Mm.egENSEMBL2EG)
diff_genes$Row.names = as.character(x[str_to_upper(diff_genes$Row.names)])
up_genes = diff_genes[diff_genes$logFC > 0, "Row.names"]
down_genes = diff_genes[diff_genes$logFC < 0, "Row.names"]
annotation = readRDS("data/devspine_genes.rds")
equi_genes = readRDS("data/equi_genes.rds")
equi_genes = str_to_lower(equi_genes)
equi_genes = data.frame(equi_genes)
equi_anno = merge(equi_genes, annotation, by.x="equi_genes", by.y="ensembl_id", all.x=TRUE, all.y=FALSE)
equi_genes = equi_genes[equi_anno$gene_biotype == "protein_coding",]
equi_genes = x[equi_genes]
```

```{r}
createGO = function(genes, ontology){
    genelist = factor(as.integer(mapped_genes %in% genes))
    names(genelist) = mapped_genes
    GO = new("topGOdata",
               ontology = ontology,
               allGenes = genelist,
               annot = annFUN.org,
               mapping = "org.Mm.eg.db",
               ID = "entrez",
               nodeSize = 5,
              )
    return(GO)
}
```

```{r}
y = org.Mm.egGO
mapped_genes = mappedkeys(y)
up_genes = createGO(up_genes, "BP")
down_genes = createGO(down_genes, "BP")
equi_genes = createGO(equi_genes, "BP")
```

```{r}
up_enrich = runTest(up_genes, algorithm="weight01",statistic="fisher")
down_enrich = runTest(down_genes, algorithm="weight01", statistic="fisher")
equi_enrich = runTest(equi_genes, algorithm="weight01", statistic="fisher")
```

```{r}
topres_up = GenTable(up_genes, classicFisher=up_enrich, orderBy="up_enrich", ranksOf="up_enrich", topNodes=25)
topres_down = GenTable(down_genes, classicFisher=down_enrich, orderBy="down_enrich", ranksOf="down_enrich", topNodes=25)
topres_equi = GenTable(equi_genes, classicFisher=equi_enrich, orderBy="equi_enrich", ranksOf="equi_enrich", topNodes=25)
```

```{r}
saveRDS(up_enrich, "data/up_enrich.rds")
saveRDS(down_enrich, "data/down_enrich.rds")
saveRDS(equi_enrich, "data/equi_enrich.rds")
saveRDS(topres_up, "data/topres_up.rds")
saveRDS(topres_down, "data/topres_down.rds")
saveRDS(topres_equi, "data/topres_equi.rds")
```
