---
jupyter:
  jupytext:
    formats: ipynb,Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r}
library(stringr)
library(org.Mm.eg.db)
library(clusterProfiler)
diff_genes = readRDS("data/sig_regulated_genes.rds")
down_genes = str_to_upper(diff_genes[diff_genes$logFC > 0, "Row.names"])
up_genes   = str_to_upper(diff_genes[diff_genes$logFC < 0, "Row.names"])
annotation = readRDS("data/devspine_genes.rds")
annotation$ensembl_id = str_to_upper(annotation$ensembl_id)
equi_genes = readRDS("data/equi_genes.rds")
equi_genes = data.frame(equi_genes)
equi_anno  = merge(equi_genes, annotation, by.x="equi_genes", by.y="ensembl_id", all.x=TRUE, all.y=FALSE)
equi_genes = equi_genes[equi_anno$gene_biotype == "protein_coding",]
```

```{r}
GOenrich = function(genes, ontology){
    ego  = enrichGO(gene          = genes,
               OrgDb         = org.Mm.eg.db,
               keyType       = "ENSEMBL",
               ont           = ontology,
               pAdjustMethod = "BY",
               pvalueCutoff  = 0.01
              )
    ego  = simplify(ego)
    return(ego)
}
```

```{r}
downGOMF = GOenrich(down_genes, "MF")
upGOMF   = GOenrich(up_genes, "MF")
equiGOMF = GOenrich(equi_genes, "MF")
```

```{r}
saveRDS(downGOMF, "data/GOanal_downMF.rds")
saveRDS(upGOMF, "data/GOanal_upMF.rds")
saveRDS(equiGOMF, "data/GOanal_equiMF.rds")
```

```{r}
downGOBP = GOenrich(down_genes, "BP")
upGOBP   = GOenrich(up_genes, "BP")
equiGOBP = GOenrich(equi_genes, "BP")
```
